{% set name = "environ-config" %}
{% set version = "22.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/environ-config-{{ version }}.tar.gz
  sha256: 7c7dbc5601060667301e992f6f0544c01e5144c86f1b2ec0b053e322788bb602

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - attrs >=17.4.0
    - python >={{ python_min }}

test:
  imports:
    - environ
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/hynek/environ_config
  summary: Boilerplate-free configuration with env variables.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asford
