{% set name = "environ-config" %}
{% set version = "23.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 3c7013910c1d4738df6b4cf379f597c6ea58b5f272cea0382b24f1eb51bff689

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.3
  run:
    - attrs >=17.4.0
    - python >=3.3

test:
  imports:
    - environ
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/hynek/environ_config
  summary: Boilerplate-free configuration with env variables.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asford
